config:
  lookupServiceDB: fda-ndc-rest
  lookupServiceURI: mongodb://localhost/fda-ndc-rest
  lookupServiceCollection: products
  defaultResultsPageSize: 20
  maxResultsPageSize: 50
  defaultFirstPage: 1