redis:
  uri: redis://localhost
  cacheTTLInSeconds: 3600
mongo:
  db: fda-ndc-rest
  collection: products
  uri: mongodb://localhost/fda-ndc-rest
api:
  defaultResultsPageSize: 20
  maxResultsPageSize: 50
  defaultFirstPage: 0
  teaserProductProperties: productNDC,proprietaryName,startMarketingDate,endMarketingDate,labelerName,substances
  sortProperties: startMarketingDate,productTypeName,marketingCategoryName,labelerName
importer:
  ndcDirectoryPage: http://www.fda.gov/Drugs/InformationOnDrugs/ucm142438.htm
  ndcDatabaseFileURL: http://www.accessdata.fda.gov/cder/ndc.zip
  refreshCheckTimeInHours: 1